version: '2'
services:
  postgres:
    image: postgres:9.6
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=costs
    dns:
     - name=postgres
