namespace costs.net.integration.tests.MaterialLedgerCodes
{
    using System;
    using System.Threading.Tasks;
    using core.Models.Costs;
    using dataAccess.Entity;
    using FluentAssertions;
    using NUnit.Framework;

    [TestFixture]
    public class ProductionCostTests : BaseMaterialLedgerCodeTest
    {
        [TestCase("MGCDigitalDigital", plugins.Constants.ContentType.Digital, null, plugins.Constants.MediaType.Digital, null, "S821018AU", "33500001")]
        [TestCase("MGCDigitalNA", plugins.Constants.ContentType.Digital, null, plugins.Constants.MediaType.NA, null, "S821018AU", "33500001")]

        [TestCase("MGCAudioFullCinemaAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullCinemaLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullCinemaOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullCinemaVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDigitalAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDigitalLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDigitalOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDigitalVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDirectToCustomerAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDirectToCustomerLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCAudioFullDirectToCustomerOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCAudioFullDirectToCustomerVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCAudioFullInStoreAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullInStoreLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "S821019BD", "34420006")]
        [TestCase("MGCAudioFullInStoreOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "S821019BD", "34420006")]
        [TestCase("MGCAudioFullInStoreVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "S821019BD", "34420006")]
        [TestCase("MGCAudioFullNAAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNALift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNAOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNAVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNotForAirAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNotForAirLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNotForAirOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNotForAirVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullOutOfHomeAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullOutOfHomeLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullOutOfHomeOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullOutOfHomeVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullPRInfluencerAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullPRInfluencerLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S82141500", "33720001")]
        [TestCase("MGCAudioFullPRInfluencerOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S82141500", "33720001")]
        [TestCase("MGCAudioFullPRInfluencerVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S82141500", "33720001")]
        [TestCase("MGCAudioFullRadioAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Radio, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullRadioLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Radio, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullRadioOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Radio, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullRadioVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Radio, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullStreamingAudioAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullStreamingAudioLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullStreamingAudioOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullStreamingAudioVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullTvAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullTvLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullTvOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullTvVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Version, "S821018AU", "33500001")]

        [TestCase("MGCAudioPostCinemaAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostCinemaLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostCinemaOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostCinemaVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDigitalAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostDigitalLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDigitalOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDigitalVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDirectToCustomerAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDirectToCustomerLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCAudioPostDirectToCustomerOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCAudioPostDirectToCustomerVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCAudioPostInStoreAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostInStoreLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "S821019BD", "34420006")]
        [TestCase("MGCAudioPostInStoreOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "S821019BD", "34420006")]
        [TestCase("MGCAudioPostInStoreVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "S821019BD", "34420006")]
        [TestCase("MGCAudioPostNAAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostNALift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNAOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNAVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNotForAirAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNotForAirLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNotForAirOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNotForAirVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostOutOfHomeAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostOutOfHomeLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostOutOfHomeOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostOutOfHomeVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostPRInfluencerAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostPRInfluencerLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S82141500", "33720001")]
        [TestCase("MGCAudioPostPRInfluencerOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S82141500", "33720001")]
        [TestCase("MGCAudioPostPRInfluencerVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S82141500", "33720001")]
        [TestCase("MGCAudioPostRadioAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Radio, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostRadioLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Radio, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostRadioOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Radio, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostRadioVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Radio, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostStreamingAudioAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostStreamingAudioLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostStreamingAudioOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostStreamingAudioVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostTvAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostTvLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Lift, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostTvOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Original, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostTvVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Version, "S821018AU", "33500001")]

        [TestCase("MGCPhotographyFullDigitalAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDigitalLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDigitalOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDigitalVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDirectToCustomerAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDirectToCustomerLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyFullDirectToCustomerOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyFullDirectToCustomerVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyFullInStoreAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullInStoreLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyFullInStoreOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyFullInStoreVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyFullNAAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNALift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNAOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNAVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNotForAirAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNotForAirLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNotForAirOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNotForAirVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullOutOfHomeAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullOutOfHomeLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullOutOfHomeOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullOutOfHomeVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullPRInfluencerAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullPRInfluencerLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S82141500", "33720001")]
        [TestCase("MGCPhotographyFullPRInfluencerOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S82141500", "33720001")]
        [TestCase("MGCPhotographyFullPRInfluencerVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S82141500", "33720001")]
        [TestCase("MGCPhotographyFullStreamingAudioAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullStreamingAudioLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullStreamingAudioOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullStreamingAudioVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AV", "33500001")]

        [TestCase("MGCPhotographyPostDigitalAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCPhotographyPostDigitalLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostDigitalOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostDigitalVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostDirectToCustomerAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostDirectToCustomerLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyPostDirectToCustomerOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyPostDirectToCustomerVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyPostInStoreAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostInStoreLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyPostInStoreOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyPostInStoreVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyPostNAAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCPhotographyPostNALift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNAOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNAVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNotForAirAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNotForAirLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNotForAirOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNotForAirVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostOutOfHomeAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCPhotographyPostOutOfHomeLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostOutOfHomeOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostOutOfHomeVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostPRInfluencerAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostPRInfluencerLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S82141500", "33720001")]
        [TestCase("MGCPhotographyPostPRInfluencerOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S82141500", "33720001")]
        [TestCase("MGCPhotographyPostPRInfluencerVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S82141500", "33720001")]
        [TestCase("MGCPhotographyPostStreamingAudioAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCPhotographyPostStreamingAudioLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostStreamingAudioOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostStreamingAudioVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AV", "33500001")]

        [TestCase("MGCVideoFullCinemaAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullCinemaLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullCinemaOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullCinemaVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Cinema, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDigitalAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDigitalLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDigitalOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDigitalVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDirectToCustomerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDirectToCustomerLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCVideoFullDirectToCustomerOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCVideoFullDirectToCustomerVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCVideoFullInStoreAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullInStoreLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "S821019BD", "34420006")]
        [TestCase("MGCVideoFullInStoreOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "S821019BD", "34420006")]
        [TestCase("MGCVideoFullInStoreVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "S821019BD", "34420006")]
        [TestCase("MGCVideoFullNAAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNALift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNAOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNAVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNotForAirAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNotForAirLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNotForAirOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNotForAirVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullOutOfHomeAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullOutOfHomeLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullOutOfHomeOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullOutOfHomeVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullPRInfluencerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullPRInfluencerLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S821019BD", "33720001")]
        [TestCase("MGCVideoFullPRInfluencerOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S821019BD", "33720001")]
        [TestCase("MGCVideoFullPRInfluencerVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S821019BD", "33720001")]
        [TestCase("MGCVideoFullStreamingAudioAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullStreamingAudioLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullStreamingAudioOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullStreamingAudioVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullTvAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullTvLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullTvOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullTvVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, plugins.Constants.MediaType.Tv, Constants.OvalType.Version, "S821018AT", "33500001")]

        [TestCase("MGCVideoPostCinemaAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostCinemaLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostCinemaOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostCinemaVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Cinema, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostDigitalAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostDigitalLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostDigitalOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostDigitalVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostDirectToCustomerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostDirectToCustomerLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCVideoPostDirectToCustomerOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCVideoPostDirectToCustomerVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCVideoPostInStoreAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostInStoreLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "S821019BD", "34420006")]
        [TestCase("MGCVideoPostInStoreOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "S821019BD", "34420006")]
        [TestCase("MGCVideoPostInStoreVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "S821019BD", "34420006")]
        [TestCase("MGCVideoPostNAAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostNALift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNAOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNAVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNotForAirAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNotForAirLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNotForAirOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNotForAirVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostOutOfHomeAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostOutOfHomeLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostOutOfHomeOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostOutOfHomeVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostPRInfluencerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostPRInfluencerLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S821019BD", "33720001")]
        [TestCase("MGCVideoPostPRInfluencerOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S821019BD", "33720001")]
        [TestCase("MGCVideoPostPRInfluencerVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S821019BD", "33720001")]
        [TestCase("MGCVideoPostStreamingAudioAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostStreamingAudioLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostStreamingAudioOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostStreamingAudioVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostTvAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostTvLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostTvOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostTvVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, plugins.Constants.MediaType.Tv, Constants.OvalType.Version, "S821018AT", "33500001")]

        [TestCase("MGCVideoCgiCinemaAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Cinema, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiCinemaLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Cinema, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiCinemaOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Cinema, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiCinemaVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Cinema, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiDigitalAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Digital, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiDigitalLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Digital, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiDigitalOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Digital, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiDigitalVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Digital, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiDirectToCustomerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiDirectToCustomerLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Lift, "G821215AA", "33710001")]
        [TestCase("MGCVideoCgiDirectToCustomerOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Original, "G821215AA", "33710001")]
        [TestCase("MGCVideoCgiDirectToCustomerVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.DirectToCustomer, Constants.OvalType.Version, "G821215AA", "33710001")]
        [TestCase("MGCVideoCgiInStoreAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.InStore, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiInStoreLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.InStore, Constants.OvalType.Lift, "S821019BD", "34420006")]
        [TestCase("MGCVideoCgiInStoreOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.InStore, Constants.OvalType.Original, "S821019BD", "34420006")]
        [TestCase("MGCVideoCgiInStoreVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.InStore, Constants.OvalType.Version, "S821019BD", "34420006")]
        [TestCase("MGCVideoCgiNAAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NA, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiNALift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NA, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNAOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NA, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNAVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NA, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNotForAirAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNotForAirLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNotForAirOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNotForAirVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.NotForAir, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiOutOfHomeAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiOutOfHomeLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiOutOfHomeOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiOutOfHomeVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.OutOfHome, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiPRInfluencerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Adaptation, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiPRInfluencerLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Lift, "S821019BD", "33720001")]
        [TestCase("MGCVideoCgiPRInfluencerOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Original, "S821019BD", "33720001")]
        [TestCase("MGCVideoCgiPRInfluencerVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.PRInfluencer, Constants.OvalType.Version, "S821019BD", "33720001")]
        [TestCase("MGCVideoCgiStreamingAudioAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiStreamingAudioLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiStreamingAudioOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiStreamingAudioVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.StreamingAudio, Constants.OvalType.Version, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiTvAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Tv, Constants.OvalType.Adaptation, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiTvLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Tv, Constants.OvalType.Lift, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiTvOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Tv, Constants.OvalType.Original, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiTvVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, plugins.Constants.MediaType.Tv, Constants.OvalType.Version, "S821018AT", "33500001")]
        
        public async Task CheckSingleMgcCodes(string costTitle, string contentType, string productionType, string mediaType, string ovalType, string expectedMgCode, string expectedGlCode)
        {
            // Arrange
            var latestRevision = await SetupProductionCost(costTitle, contentType, productionType, new[] { mediaType }, new[] { ovalType });

            // Act
            var b = await LedgerMaterialCodeService.GetLedgerMaterialCodes(latestRevision.Id);

            // Assert
            b.Should().NotBeNull();
            b.GlCode.Should().Be(expectedGlCode);
            b.MgCode.Should().Be(expectedMgCode);
        }

        [TestCase("MGCDigitalMultiple", plugins.Constants.ContentType.Digital, null, new[]{ plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.NA }, new string[]{ null }, "S821018AU", "33500001")]
        
        [TestCase("MGCAudioFullMultipleAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[]{ Constants.OvalType.Adaptation }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullMultipleLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[]{ Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullMultipleOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[]{ Constants.OvalType.Original }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullMultipleVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[]{ Constants.OvalType.Version }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullCinemaMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDigitalMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullDirectToCustomerMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "G821215AA", "33710001")]
        [TestCase("MGCAudioFullInStoreMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821019BD", "34420006")]
        [TestCase("MGCAudioFullNAMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullNotForAirMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullOutOfHomeMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullPRInfluencerMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S82141500", "33720001")]
        [TestCase("MGCAudioFullRadioMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Radio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullStreamingAudioMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullTvMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Tv }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioFullMultipleMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]

        [TestCase("MGCAudioPostMultipleAdaptation", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCAudioPostMultipleLift", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostMultipleOriginal", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Original }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostMultipleVersion", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Version }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostCinemaMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDigitalMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostDirectToCustomerMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "G821215AA", "33710001")]
        [TestCase("MGCAudioPostInStoreMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821019BD", "34420006")]
        [TestCase("MGCAudioPostNAMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostNotForAirMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostOutOfHomeMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostPRInfluencerMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S82141500", "33720001")]
        [TestCase("MGCAudioPostRadioMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Radio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostStreamingAudioMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostTvMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Tv }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]
        [TestCase("MGCAudioPostMultipleMultiple", plugins.Constants.ContentType.Audio, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AU", "33500001")]

        [TestCase("MGCPhotographyFullMultipleAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullMultipleLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullMultipleOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Original }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullMultipleVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Version }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDigitalMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullDirectToCustomerMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyFullInStoreMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyFullNAMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullNotForAirMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullOutOfHomeMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullPRInfluencerMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S82141500", "33720001")]
        [TestCase("MGCPhotographyFullStreamingAudioMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyFullMultipleMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.PRInfluencer, plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]

        [TestCase("MGCPhotographyPostMultipleAdaptation", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCPhotographyPostMultipleLift", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostMultipleOriginal", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Original }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostMultipleVersion", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital, plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Version }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostDigitalMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostDirectToCustomerMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "G821215AA", "33710001")]
        [TestCase("MGCPhotographyPostInStoreMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "G821215AA", "34420005")]
        [TestCase("MGCPhotographyPostNAMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostNotForAirMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostOutOfHomeMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostPRInfluencerMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S82141500", "33720001")]
        [TestCase("MGCPhotographyPostStreamingAudioMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]
        [TestCase("MGCPhotographyPostMultipleMultiple", plugins.Constants.ContentType.Photography, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.PRInfluencer, plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AV", "33500001")]

        [TestCase("MGCVideoFullMultipleAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullMultipleLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Lift }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullMultipleOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Original }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullMultipleVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Version }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullCinemaAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[]{ plugins.Constants.MediaType.Cinema }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDigitalAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullDirectToCustomerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullInStoreAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNAAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullNotForAirAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullOutOfHomeAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullPRInfluencerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullStreamingAudioAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullTvAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Tv }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoFullMultipleMultiple", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.FullProduction, new[] { plugins.Constants.MediaType.Tv, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AT", "33500001")]

        [TestCase("MGCVideoPostMultipleAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostMultipleLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Lift }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostMultipleOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Original }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostMultipleVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Version }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostCinemaAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Cinema }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostDigitalAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostDirectToCustomerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostInStoreAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostNAAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostNotForAirAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostOutOfHomeAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostPRInfluencerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoPostStreamingAudioAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostTvAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Tv }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoPostMultipleMultiple", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.PostProductionOnly, new[] { plugins.Constants.MediaType.Tv, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AT", "33500001")]

        [TestCase("MGCVideoCgiMultipleAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiMultipleLift", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Lift }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiMultipleOriginal", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Original }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiMultipleVersion", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Cinema, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Version }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiCinemaAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Cinema }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiDigitalAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiDirectToCustomerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.DirectToCustomer }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiInStoreAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.InStore }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiNAAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.NA }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiNotForAirAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.NotForAir }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiOutOfHomeAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.OutOfHome }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiPRInfluencerAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.PRInfluencer }, new[] { Constants.OvalType.Adaptation }, "S821018AT", "33500001")]
        [TestCase("MGCVideoCgiStreamingAudioAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.StreamingAudio }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiTvAdaptation", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Tv }, new[] { Constants.OvalType.Adaptation }, "S821018BI", "33500005")]
        [TestCase("MGCVideoCgiMultipleMultiple", plugins.Constants.ContentType.Video, plugins.Constants.ProductionType.CgiAnimation, new[] { plugins.Constants.MediaType.Tv, plugins.Constants.MediaType.Digital }, new[] { Constants.OvalType.Adaptation, Constants.OvalType.Lift }, "S821018AT", "33500001")]
        
        public async Task CheckMultipleMgcCodes(string costTitle, string contentType, string productionType, string[] mediaTypes, string[] ovalTypes, string expectedMgCode, string expectedGlCode)
        {
            // Arrange
            var latestRevision = await SetupProductionCost(costTitle, contentType, productionType, mediaTypes, ovalTypes);

            // Act
            var b = await LedgerMaterialCodeService.GetLedgerMaterialCodes(latestRevision.Id);

            // Assert
            b.Should().NotBeNull();
            b.GlCode.Should().Be(expectedGlCode);
            b.MgCode.Should().Be(expectedMgCode);
        }

        private async Task<CostStageRevision> SetupProductionCost(string costTitle, string contentType, string productionType, string[] mediaTypes, string[] ovalTypes)
        {
            var cost = await CreateProductionCost(User, costTitle, contentType, productionType);
            var latestStage = await GetCostLatestStage(cost.Id, User);
            var latestRevision = await GetCostLatestRevision(cost.Id, latestStage.Id, User);

            foreach (var mediaType in mediaTypes)
            {
                foreach (var ovalType in ovalTypes)
                {
                    var mediaTypeId = await GetMediaTypeId(mediaType);

                    Guid? ovalTypeId = null;
                    if (!string.IsNullOrEmpty(ovalType))
                    {
                        ovalTypeId = await GetOvalTypeId(ovalType);
                    }

                    await CreateMediaTypeMappingIfNotCreated(mediaTypeId);
                    await CreateExpectedAsset(cost.Id, latestStage.Id, latestRevision.Id, new CreateExpectedAssetModel
                    {
                        Title = "Title1",
                        AdId = Guid.NewGuid().ToString().Replace("-", string.Empty).Substring(0, 12),
                        AiringRegions = new[] { "EMEA" },
                        Duration = TimeSpan.FromHours(1).ToString(),
                        Definition = "HD",
                        MediaTypeId = mediaTypeId,
                        OvalTypeId = ovalTypeId,
                        FirstAirDate = DateTime.UtcNow.AddDays(5),
                        AssetId = "ADGADG",
                        Scrapped = false
                    });
                }
            }
            
            await LedgerMaterialCodeService.UpdateLedgerMaterialCodes(latestRevision.Id);
            return latestRevision;
        }
    }
}
